language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
install:
  - pip install unittest2 future
script: python -m unittest2.__main__ fastimport.tests.test_suite
